////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////

////
END GENERATED ATTRIBUTES
////


[id="chap-getting-started"]
= Getting Started with {product-eap} on OpenShift using a Helm Chart
ifdef::context[:parent-context: {context}]
:context: getting-started


ifdef::qs[]
[#description]
====
Deploy a simple {product-eap} application on OpenShift using a Helm Chart.
====

[#introduction]
====
[Red Hat® JBoss® Enterprise Application Platform (EAP)](https://www.redhat.com/en/technologies/jboss-middleware/application-platform) is an application server. It includes everything needed to build, run, deploy, and manage enterprise Java applications in a variety of environments, including on-premise, virtual environments, and in private, public, and hybrid clouds.

* **Optimized for OpenShift, Cloud and Containers**
* **Jakarta EE 8 compatibility**
* **Lightweight, flexible architecture**
* **Red Hat Portfolio Integration**
* **More productive developers with DevOps and Agile Development**
In this quickstart, you will deploy and run a [Jakarta EE application](https://github.com/jboss-eap-up-and-running/eap7-getting-started) with JBoss EAP 7 on OpenShift.

**Note:** The quickstart uses a sample [Jakarta EE application](https://github.com/jboss-eap-up-and-running/eap7-getting-started). You can deploy your own Jakarta EE application using the same steps.
The quickstart has instructions where changes would be needed (Task 1).
====

[id="proc-creating-kafka-instance_{context}"]
== Create a JBoss EAP7 application with Helm
To create a JBoss EAP 7 application:

.Procedure
. In the main navigation, click the dropdown menu [perspective switcher]{{highlight qs-perspective-switcher}} and select **Developer**.
. In the navigation menu, click [Add]{{highlight qs-nav-add}}/
+
The **Add** page opens.
+
. In the **Add** page, click **Helm Chart**.
. In the ** Helm Charts** catalog, search for **JBoss EAP 7.4**
- The side panel displays information about the JBoss EAP 7 Helm Chart
// TODO add more steps



endif::[]



// Rendering for GitHub
== The Application
The `src/main` folder contains a simple 'Hello world' style Jakarta EE application using JAX-RS.

== Deploying the Quickstart

Make sure you have done all the https://github.com/jboss-eap-up-and-running/docs/blob/main/RUNNING_ON_OPENSHIFT.adoc#prerequisites[prerequisites] and https://github.com/jboss-eap-up-and-running/docs/blob/main/RUNNING_ON_OPENSHIFT.adoc#selecting_creating_a_project[selected/created a project].

Then install the Helm chart contained under link:./charts/helm.yaml[charts/helm.yaml] to install the application into OpenShift.
[source,shell]
----
helm install eap7-getting-started -f charts/helm.yaml jboss-eap/eap74
----
See the https://github.com/jboss-eap-up-and-running/docs/blob/main/RUNNING_ON_OPENSHIFT.adoc#deploying_with_helm[Deploying with Helm] section for information about when the application will be ready.

== Running the application

To run the application, you can access it through its OpenShift route:

[source,shell]
----
echo https://$(oc get route eap7-getting-started --template='{{ .spec.host }}')
----

If you use this URL, you will see the welcome page of the application.

== Explaining the application configuration

This application is extremely simple, so apart from the standard information in https://github.com/jboss-eap-up-and-running/docs/blob/main/RUNNING_ON_OPENSHIFT.adoc#introduction_to_helm_charts[Introduction to Helm Charts], link:./charts/helm.yaml[./charts/helm.yaml] contains no additional information.


ifdef::qs[]
[#conclusion]
====
Your JBoss EAP 7 application is deployed and ready.

## Resources:
  - Learn more about  [JBoss EAP](https://access.redhat.com/products/red-hat-jboss-enterprise-application-platform/).
  - Read detailed [JBoss EAP 7 documentation](https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4).
====
endif::[]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]